import { ComponentType } from "react";
import {
  Home,
  Calendar,
  Users,
  UserPlus,
  Plus,
  Sliders,
  TrendingUp,
  SlidersHorizontal,
  ClipboardCheck,
  Target,
  Trophy,
  Settings,
  History,
  Activity,
  FileText,
  Building,
  MapPin
} from "lucide-react";
import { Capability, TournamentRole, GlobalRole } from "./permissions";

export type WorkflowStage =
  | "draft"
  | "registration"
  | "ready"
  | "live"
  | "completed"
  | "archived";

export interface WorkspaceConfig {
  id: string;
  title: string;
  description: string;
  icon: ComponentType<any>;
  order: number;
  parentWorkspace: string | null;
  childTabs?: string[];
  repositoryOwner: string;
  businessEngineOwner: string;
  workflowVisibility: WorkflowStage[] | "all";
  requiredCapabilities: Capability[];
  allowedTournamentRoles: TournamentRole[] | "all";
  allowedGlobalRoles: GlobalRole[] | "all";
  routeContextBinding: "global" | "tournament";
  visibilityConditions?: (state: {
    activeHistoryId: string | null;
    currentTournamentDoc: any;
    globalRole: GlobalRole;
    tournamentRole: TournamentRole;
  }) => boolean;
}

export const WORKSPACE_MANIFEST: WorkspaceConfig[] = [
  // ================= GLOBAL WORKSPACES =================
  {
    id: "home",
    title: "Trang Chủ",
    description: "Hệ thống điều hành bắn súng cao su VSC Platform",
    icon: Home,
    order: 1,
    parentWorkspace: null,
    repositoryOwner: "System Repository",
    businessEngineOwner: "Platform Core",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "global",
  },
  {
    id: "tournaments",
    title: "Quản Lý Giải Đấu",
    description: "Danh sách các giải đấu trực tuyến và trực tiếp",
    icon: Calendar,
    order: 2,
    parentWorkspace: null,
    repositoryOwner: "Tournament Repository",
    businessEngineOwner: "Platform Core",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId,
  },
  {
    id: "athletes",
    title: "Athlete (Vận động viên)",
    description: "Hồ sơ vận động viên hệ thống độc lập",
    icon: Users,
    order: 3,
    parentWorkspace: null,
    repositoryOwner: "Athlete Registry",
    businessEngineOwner: "Master Data Management",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId,
  },
  {
    id: "clubs",
    title: "Club (Câu lạc bộ)",
    description: "Hồ sơ câu lạc bộ và cổng hoạt động thành viên",
    icon: Building,
    order: 4,
    parentWorkspace: null,
    repositoryOwner: "Club Registry",
    businessEngineOwner: "Club Portal Management",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId,
  },
  {
    id: "provinces",
    title: "Tỉnh/Thành (Province)",
    description: "Bảng phân bổ danh tính xạ thủ và câu lạc bộ theo địa phương",
    icon: MapPin,
    order: 5,
    parentWorkspace: null,
    repositoryOwner: "Province Registry",
    businessEngineOwner: "Province Portal Management",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId,
  },
  {
    id: "seasons",
    title: "Mùa Giải (Season)",
    description: "Cơ sở dữ liệu các mùa giải và xếp hạng tích lũy quốc gia",
    icon: Trophy,
    order: 6,
    parentWorkspace: null,
    repositoryOwner: "Season Registry",
    businessEngineOwner: "Season Portal Management",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId,
  },
  {
    id: "hall_of_fame",
    title: "Đại Sảnh Danh Vọng",
    description: "Tôn vinh những xạ thủ xuất sắc nhất, các nhà vô địch và kỷ lục gia VSC",
    icon: Trophy,
    order: 6.5,
    parentWorkspace: null,
    repositoryOwner: "Ranking Engine",
    businessEngineOwner: "Ranking Calculation Engine",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId,
  },
  {
    id: "control_panel",
    title: "Bảng Điều Khiển",
    description: "Hồ sơ cá nhân và quản trị phân quyền",
    icon: Sliders,
    order: 7,
    parentWorkspace: null,
    repositoryOwner: "User Registry",
    businessEngineOwner: "Platform Control Panel",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId,
  },
  {
    id: "users",
    title: "Tài Khoản & Phân Quyền",
    description: "Quản trị phân quyền tài khoản, vai trò và liên kết VĐV gốc",
    icon: Sliders,
    order: 8,
    parentWorkspace: null,
    repositoryOwner: "User Registry",
    businessEngineOwner: "User Portal Management",
    workflowVisibility: "all",
    requiredCapabilities: ["global.manage_users"],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: ["system_owner", "admin"],
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId && (state.globalRole === "system_owner" || state.globalRole === "admin"),
  },
  {
    id: "referees",
    title: "Ban Trọng Tài",
    description: "Cơ sở dữ liệu danh sách trọng tài hệ thống và số hiệu badge",
    icon: Settings,
    order: 9,
    parentWorkspace: null,
    repositoryOwner: "Referee Registry",
    businessEngineOwner: "Referee Portal Management",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: ["system_owner", "admin"],
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId && (state.globalRole === "system_owner" || state.globalRole === "admin"),
  },
  {
    id: "sponsors",
    title: "Nhà Tài Trợ",
    description: "Danh sách nhà tài trợ đồng hành, thương hiệu và liên kết website",
    icon: Trophy,
    order: 10,
    parentWorkspace: null,
    repositoryOwner: "Sponsor Registry",
    businessEngineOwner: "Sponsor Portal Management",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: ["system_owner", "admin"],
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId && (state.globalRole === "system_owner" || state.globalRole === "admin"),
  },
  {
    id: "rule_templates",
    title: "Bản Mẫu Quy Chế",
    description: "Quản lý và tinh chỉnh các bản mẫu quy chế giải đấu mẫu",
    icon: FileText,
    order: 11,
    parentWorkspace: null,
    repositoryOwner: "Template Registry",
    businessEngineOwner: "Template Portal Management",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: ["system_owner", "admin"],
    routeContextBinding: "global",
    visibilityConditions: (state) => !state.activeHistoryId && (state.globalRole === "system_owner" || state.globalRole === "admin"),
  },

  // ================= TOURNAMENT WORKSPACES =================
  {
    id: "dashboard",
    title: "Tổng Quan (Overview)",
    description: "Số liệu thống kê, sơ đồ phân bổ và biểu đồ trực quan giải đấu",
    icon: TrendingUp,
    order: 10,
    parentWorkspace: "tournament_workspace",
    repositoryOwner: "Tournament Repository",
    businessEngineOwner: "Dashboard Engine",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "tournament",
    visibilityConditions: (state) => !!state.activeHistoryId,
  },
  {
    id: "public_registration",
    title: "Đăng Ký Thi Đấu",
    description: "Cổng đăng ký tham dự giải đấu và nộp lệ phí trực tuyến dành cho VĐV",
    icon: UserPlus,
    order: 10.5,
    parentWorkspace: "tournament_workspace",
    repositoryOwner: "Tournament Repository",
    businessEngineOwner: "Rules Engine",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "tournament",
    visibilityConditions: (state) => !!state.activeHistoryId,
  },
  {
    id: "command_center",
    title: "Mission Control (Tác Chiến)",
    description: "Quản trị bệ bắn thời gian thực, quản lý lượt bắn và gán trọng tài",
    icon: SlidersHorizontal,
    order: 11,
    parentWorkspace: "tournament_workspace",
    repositoryOwner: "Assignment Engine",
    businessEngineOwner: "Mission Control Core",
    workflowVisibility: ["ready", "live"],
    requiredCapabilities: ["assignment.generate"],
    allowedTournamentRoles: ["sub_admin", "tournament_director", "tournament_owner"],
    allowedGlobalRoles: "all",
    routeContextBinding: "tournament",
    visibilityConditions: (state) => !!state.activeHistoryId,
  },
  {
    id: "tournament_mgmt",
    title: "Quản Lý & Vận Hành",
    description: "Phê duyệt đăng ký, điểm danh kiểm tra và gán bệ bắn cho vận động viên",
    icon: Calendar,
    order: 12,
    parentWorkspace: "tournament_workspace",
    repositoryOwner: "Tournament Repository",
    businessEngineOwner: "Rules Engine",
    workflowVisibility: ["draft", "registration", "ready"],
    requiredCapabilities: ["participants.manage"],
    allowedTournamentRoles: ["sub_admin", "tournament_director", "tournament_owner"],
    allowedGlobalRoles: "all",
    routeContextBinding: "tournament",
    visibilityConditions: (state) => !!state.activeHistoryId,
  },
  {
    id: "input_scores",
    title: "Referee Terminal (Ghi Điểm)",
    description: "Nhập điểm thời gian thực trực tuyến theo phân khu bệ bắn được giao",
    icon: ClipboardCheck,
    order: 13,
    parentWorkspace: "tournament_workspace",
    repositoryOwner: "Score Validation Engine",
    businessEngineOwner: "Live Score Input Engine",
    workflowVisibility: ["live"],
    requiredCapabilities: ["score.enter"],
    allowedTournamentRoles: ["referee", "head_referee", "tournament_director", "tournament_owner"],
    allowedGlobalRoles: "all",
    routeContextBinding: "tournament",
    visibilityConditions: (state) => !!state.activeHistoryId,
  },
  {
    id: "scoring",
    title: "Official Score Ledger",
    description: "Sổ cái lưu trữ lịch sử chấm điểm, audit log và các phiên bản sửa đổi",
    icon: Target,
    order: 14,
    parentWorkspace: "tournament_workspace",
    repositoryOwner: "Official Ledger Repository",
    businessEngineOwner: "Score Validation Engine",
    workflowVisibility: ["live", "completed", "archived"],
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "tournament",
    visibilityConditions: (state) => !!state.activeHistoryId,
  },
  {
    id: "leaderboard",
    title: "Ranking",
    description: "Bảng xếp hạng cá nhân và đồng đội thời gian thực",
    icon: Trophy,
    order: 15,
    parentWorkspace: "tournament_workspace",
    repositoryOwner: "Ranking Engine",
    businessEngineOwner: "Ranking Calculation Engine",
    workflowVisibility: ["ready", "live", "completed", "archived"],
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "tournament",
    visibilityConditions: (state) => !!state.activeHistoryId,
  },
  {
    id: "history",
    title: "Nhật Ký (Audit Log)",
    description: "Nhật ký lưu trữ kiểm toán toàn diện tất cả thao tác của trọng tài",
    icon: History,
    order: 18,
    parentWorkspace: "tournament_workspace",
    repositoryOwner: "System Log Repository",
    businessEngineOwner: "Audit Engine",
    workflowVisibility: "all",
    requiredCapabilities: ["audit.view"],
    allowedTournamentRoles: ["referee", "head_referee", "sub_admin", "tournament_director", "tournament_owner"],
    allowedGlobalRoles: "all",
    routeContextBinding: "tournament",
    visibilityConditions: (state) => !!state.activeHistoryId,
  },
  {
    id: "control_panel",
    title: "Bảng Điều Khiển",
    description: "Hồ sơ cá nhân và quản trị phân quyền",
    icon: Sliders,
    order: 19,
    parentWorkspace: "tournament_workspace",
    repositoryOwner: "User Registry",
    businessEngineOwner: "Platform Control Panel",
    workflowVisibility: "all",
    requiredCapabilities: [],
    allowedTournamentRoles: "all",
    allowedGlobalRoles: "all",
    routeContextBinding: "tournament",
    visibilityConditions: (state) => !!state.activeHistoryId,
  }
];
