export const VIETNAM_PROVINCES = [
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cần Thơ",
  "Cao Bằng",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "TP. Hồ Chí Minh",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái"
];

export const WORLD_COUNTRIES = [
  "Việt Nam",
  "Afghanistan",
  "Ai Cập (Egypt)",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anh (United Kingdom)",
  "Antigua và Barbuda",
  "Áo (Austria)",
  "Ả Rập Xê Út (Saudi Arabia)",
  "Argentina",
  "Armenia",
  "Ấn Độ (India)",
  "Azerbaijan",
  "Ba Lan (Poland)",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Bạch Nga (Belarus)",
  "Bỉ (Belgium)",
  "Belize",
  "Benin",
  "Bhutan",
  "Bồ Đào Nha (Portugal)",
  "Bolivia",
  "Bosnia và Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Các Tiểu vương quốc Ả Rập Thống nhất (UAE)",
  "Cameroon",
  "Campuchia (Cambodia)",
  "Canada",
  "Chile",
  "Colombia",
  "Comoros",
  "Cộng hòa Congo",
  "Cộng hòa Dân chủ Congo",
  "Cộng hòa Dominica",
  "Cộng hòa Séc (Czech Republic)",
  "Cộng hòa Trung Phi",
  "Costa Rica",
  "Cô-tê Đ'I-vua (Ivory Coast)",
  "Croatia",
  "Cuba",
  "Djibouti",
  "Dominica",
  "Đài Loan (Taiwan)",
  "Đan Mạch (Denmark)",
  "Đông Timor (Timor-Leste)",
  "Đức (Germany)",
  "Ecuador",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Gabon",
  "Gambia",
  "Georgia",
  "Ghana",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Hà Lan (Netherlands)",
  "Haiti",
  "Hàn Quốc (South Korea)",
  "Hoa Kỳ (United States)",
  "Honduras",
  "Hồng Kông (Hong Kong)",
  "Hungary",
  "Hy Lạp (Greece)",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Jamaica",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Lào (Laos)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Ma Cao (Macau)",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritanie",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mông Cổ (Mongolia)",
  "Montenegro",
  "Ma-rốc (Morocco)",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nam Phi (South Africa)",
  "Nam Sudan",
  "Nepal",
  "New Zealand",
  "Nga (Russia)",
  "Nhật Bản (Japan)",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Na Uy (Norway)",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Pháp (France)",
  "Phần Lan (Finland)",
  "Philippines",
  "Qatar",
  "Romania",
  "Rwanda",
  "Saint Kitts và Nevis",
  "Saint Lucia",
  "Saint Vincent và Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome và Principe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Síp (Cyprus)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Thụy Điển (Sweden)",
  "Thụy Sĩ (Switzerland)",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Tây Ban Nha (Spain)",
  "Thái Lan (Thailand)",
  "Togo",
  "Tonga",
  "Trinidad và Tobago",
  "Triều Tiên (North Korea)",
  "Tunisia",
  "Thổ Nhĩ Kỳ (Turkey)",
  "Turkmenistan",
  "Tuvalu",
  "Úc (Australia)",
  "Uganda",
  "Ukraine",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Ý (Italy)",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
